# version: '3.8'
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" /mnt/data
  ports:
    - "9000:9000"
    - "9001:9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: U_CAFE
    volumes:
#      - db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

#  minio:
#    image: minio/minio
#    container_name: minio
#    environment:
#      - MINIO_ROOT_USER=abcd
#      - MINIO_ROOT_PASSWORD=abcd2345
#      - MINIO_DEFAULT_BUCKETS=buck1
#    networks:
#      mynet:
#        aliases:
#          - my-localhost  # Alias for localhost access
#    volumes:
#      - minio_data:/data
#    ports:
#      - "9001:9001"
#      - "9000:9000"
#  minio:
#    image: quay.io/minio/minio:latest
#    container_name: minio
#    restart: always
#    ports:
#      - "9000:9000"  # API Port
#      - "9001:9001"  # Console Port
#    environment:
#      MINIO_ROOT_USER: admin
#      MINIO_ROOT_PASSWORD: Ams@2025
#    volumes:
#      - ./minio:/data
#    command: server /data --console-address ":9001"

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - type: bind
        source: /mnt/data/compose
        target: /mnt/data
      - type: bind
        source: /etc/default/minio
        target: /etc/config.env


volumes:
  db:
    driver:
      local