#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: requestratelimiter_route
#          uri: https://example.org
#          filters:
#            - name: RequestRateLimiter
#              args:
#                bucket4j-rate-limiter.capacity: 20
#                bucket4j-rate-limiter.refillTokens: 10
#                bucket4j-rate-limiter.refillPeriod: 1s
#                bucket4j-rate-limiter.requestedTokens: 1

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8088/
#  config:
#    import: "configserver:" # Use the default name "configserver"
#  application:
#    name: file-service

#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: file-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/files/** #Only forward requests whose URL path matches /files/** to this service.

#spring.main.web-application-type=reactive