sprinf.application.name=POS
spring.data.mongodb.uri=mongodb://root:1234@localhost:27017/U_CAFE?authSource=admin
mongock.migration-scan-package=com.example.demo.config

#debug=true
#logging.level.root=TRACE
#logging.level.io.mongock=TRACE
#logging.level.org.springframework=TRACE
logging.level.org.springframework.security=DEBUG

jwt.signing-secret=b3BlbnRha3MtdGVzdGluZy1rZXktNTg2YzY4MmJhYjY2NTI0MGM0Y2JkMDY0Nzc2YmFhMmY
web-client.url: http://localhost:8088

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mvc.problemdetails.enabled=true