sprinf.application.name=POS
spring.data.mongodb.uri=mongodb://root:1234@localhost:27017/U_CAFE?authSource=admin
mongock.migration-scan-package=com.example.demo.config

#debug=true
#logging.level.root=TRACE
#logging.level.io.mongock=TRACE
#logging.level.org.springframework=TRACE
logging.level.org.springframework.security=DEBUG

jwt.signing-secret=SOmeRandomValuesTOExplain